<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

namespace Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.ClientViewResponse</code>
 */
class ClientViewResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.grpc.Client client = 1;</code>
     */
    protected $client = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Grpc\Client $client
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schema::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.grpc.Client client = 1;</code>
     * @return \Grpc\Client|null
     */
    public function getClient()
    {
        return isset($this->client) ? $this->client : null;
    }

    public function hasClient()
    {
        return isset($this->client);
    }

    public function clearClient()
    {
        unset($this->client);
    }

    /**
     * Generated from protobuf field <code>.grpc.Client client = 1;</code>
     * @param \Grpc\Client $var
     * @return $this
     */
    public function setClient($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Client::class);
        $this->client = $var;

        return $this;
    }

}

