<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

namespace GPBMetadata;

class Schema
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ö
schema.protogrpc"7
Client

id (
name (	
description (	"
ClientViewRequest

id ("2
ClientViewResponse
client (2.grpc.Client"
ClientIndexRequest"4
ClientIndexResponse
clients (2.grpc.Clientbproto3'
        , true);

        static::$is_initialized = true;
    }
}

